### ISSUE TITLE
ERROR while installing ocamlgraph.1.8.7 (missing separator)

### ISSUE THREAD

**Issue by twopoint718** [backtracking/ocamlgraph#62] opened 2017-08-02 02:53 UTC
I'm running the following versions:

```
> ocaml --version
The OCaml toplevel, version 4.03.0
> opam --version
1.2.2
```
And while running:

```
> opam install mirage
```

(mirage 3.0.4)

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of ocamlgraph failed at "make".
Processing  1/3: [ocamlgraph: ocamlfind remove]
#=== ERROR while installing ocamlgraph.1.8.7 ==================================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/chris/.opam/mirage-version/build/ocamlgraph.1.8.7
# compiler     4.03.0
# exit-code    2
# env-file     /Users/chris/.opam/mirage-version/build/ocamlgraph.1.8.7/ocamlgraph-84631-d8a4ae.env
# stdout-file  /Users/chris/.opam/mirage-version/build/ocamlgraph.1.8.7/ocamlgraph-84631-d8a4ae.out
# stderr-file  /Users/chris/.opam/mirage-version/build/ocamlgraph.1.8.7/ocamlgraph-84631-d8a4ae.err
### stderr ###
# Makefile:38: *** missing separator.  Stop.
```

Any insight into obvious gotchas?

**Comment by yakobowski** [comment] 2019-02-19 21:33
Unable to reproduce, so closing.

**Closed by yakobowski** 2019-02-19 21:33 UTC
